### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by turntlabs** [eonist/FlowLayout#1]
Build input files cannot be found: '/FlowLayout-master/FlowLayout/view/header/button/HeaderButton2.swift', 
'/FlowLayout-master/FlowLayout/view/cell/horizontal/HorCellKind.swift', 
'/FlowLayout-master/FlowLayout/view/cell/horizontal/HorCell+Create.swift', 
'/FlowLayout-master/FlowLayout/view/cell/horizontal/HorCell+Const.swift'

Also, even if I removed those missing files from the project, the app will crash in HorView+Collection.swift line 28.

**Comment by eonist** [comment]
Hey old sport. Now fixed. Make sure you have the latest Xcode. Download the project and run it and it should work right out of the box. Let me know if anything is unclear. It was a 1 week sprint prototype and hasn't gotten updates since. It works though, and the architecture isn't half bad. IMO. Just rough around the edges I suppose. Let me know if anything.✌️

I should add Carthage to it as well. Let's see if I can do it later tonight :)

**Comment by turntlabs** [comment]
Excellent, working now 👌🏻. Love the stuff you've done especially your blog posts. Keep up the great work. Cheers
